"""
Technical Solution Blueprint Service for [STUDIO_NAME]
Strictly conforms to DOC-PRD-005 and DOC-ARCH-003.

Enforces:
1. Strict segregation between [AI-GENERATED DRAFT] and [HUMAN-APPROVED] content (BD-010).
2. Assembly of all 18 canonical architectural sections.
3. Idempotent re-synthesis on backtracking.
"""

from typing import Optional
import uuid
from sqlalchemy.orm import Session

from app.database.models import (
    BlueprintSection,
    DiscoverySession,
    Opportunity,
    ProblemStatement,
    SolutionBlueprint,
    StructuredContext,
)
from app.modules.blueprint.canonical_sections import (
    CANONICAL_BLUEPRINT_SECTIONS,
    SectionDefinition,
)
from app.shared.logging import get_logger

logger = get_logger(__name__)

DRAFT_BANNER_MARKDOWN = (
    "> [!IMPORTANT]\n"
    "> **[AI-GENERATED DRAFT BLUEPRINT]**\n"
    "> *This architectural blueprint is an algorithmic preliminary synthesis generated by the "
    "`[STUDIO_NAME]` Discovery Engine. Final technical validation, security boundaries, and "
    "binding commercial terms strictly require formal review by a licensed Principal Architect.*\n\n"
)


class BlueprintService:
    """
    Coordinates synthesis, 18-section population, and SQL Server persistence
    of the Technical Solution Blueprint (Stage 5 deliverable).
    """

    def generate_draft_blueprint(
        self,
        db: Session,
        session: DiscoverySession,
    ) -> SolutionBlueprint:
        """
        Assembles the complete 18-section architectural blueprint draft
        persisting it idempotently to dbo.solution_blueprints and dbo.blueprint_sections.
        """
        session_id = session.id
        logger.info(f"Generating 18-section Solution Blueprint draft for session {session_id}")

        problem = db.query(ProblemStatement).filter(ProblemStatement.session_id == session_id).first()
        context = db.query(StructuredContext).filter(StructuredContext.session_id == session_id).first()
        opps = (
            db.query(Opportunity)
            .filter(Opportunity.session_id == session_id)
            .order_by(Opportunity.created_at.asc())
            .all()
        )

        problem_summary = problem.sanitized_text if problem else "Operational systems optimization"
        core_challenge = context.core_challenge if context else "Cross-system synchronization and automation"
        complexity_tier = context.complexity_tier if context else "MEDIUM"

        recommended_stack = "Python / FastAPI / SQL Server / Alpine.js / HTMX"
        exec_summary = (
            f"Bespoke technology intervention addressing: {core_challenge}. "
            f"The proposed architecture utilizes a Python-first Modular Monolith with Microsoft SQL Server "
            f"persistence, eliminating manual operational bottlenecks and establishing reliable automated workflows."
        )

        # Check for existing blueprint to support idempotent re-synthesis
        blueprint = (
            db.query(SolutionBlueprint)
            .filter(SolutionBlueprint.session_id == session_id)
            .first()
        )

        if not blueprint:
            blueprint = SolutionBlueprint(
                session_id=session_id,
                blueprint_version=1,
                recommended_stack_category=recommended_stack,
                executive_summary=exec_summary,
                status="DRAFT",
                is_architect_endorsed=False,
            )
            db.add(blueprint)
            db.flush()
        else:
            blueprint.recommended_stack_category = recommended_stack
            blueprint.executive_summary = exec_summary
            blueprint.status = "DRAFT"
            blueprint.is_architect_endorsed = False
            blueprint.blueprint_version += 1
            # Remove old sections for clean replacement
            old_sections = db.query(BlueprintSection).filter(BlueprintSection.blueprint_id == blueprint.id).all()
            for s in old_sections:
                db.delete(s)
            db.flush()

        # Build content for all 18 canonical sections
        for sec_def in CANONICAL_BLUEPRINT_SECTIONS:
            content = self._synthesize_section_content(
                sec_def=sec_def,
                problem_summary=problem_summary,
                core_challenge=core_challenge,
                complexity_tier=complexity_tier,
                opportunities=opps,
            )

            db_sec = BlueprintSection(
                blueprint_id=blueprint.id,
                section_index=sec_def.index,
                section_key=sec_def.key,
                section_title=sec_def.title,
                content_markdown=content,
                is_human_reviewed=False,
            )
            db.add(db_sec)

        db.flush()
        logger.info(f"Generated 18 blueprint sections for session {session_id}")
        return blueprint

    def _synthesize_section_content(
        self,
        sec_def: SectionDefinition,
        problem_summary: str,
        core_challenge: str,
        complexity_tier: str,
        opportunities: list[Opportunity],
    ) -> str:
        """Synthesizes structured markdown content for each of the 18 canonical sections."""
        idx = sec_def.index

        if idx == 1:
            # Executive Summary
            return (
                f"{DRAFT_BANNER_MARKDOWN}### Executive Overview\n\n"
                f"This document outlines a targeted systems engineering intervention for the operational "
                f"friction identified during discovery: **{core_challenge}**.\n\n"
                f"By replacing fragile, manual steps with an automated **Python-first Modular Monolith** "
                f"integrated with Microsoft SQL Server, this solution eliminates data re-entry, accelerates workflow "
                f"cycle time, and provides transparent audit trails for management."
            )

        elif idx == 2:
            # Problem Understanding
            return (
                f"### Root Cause vs. Symptoms\n\n"
                f"- **Reported Friction**: {problem_summary}\n"
                f"- **Core Root Cause**: {core_challenge}\n"
                f"- **Assessed Complexity**: `{complexity_tier}` systems engineering effort.\n\n"
                f"Rather than treating surface symptoms with disconnected scripts, the intervention establishes a "
                f"single source of truth and automated integration pipelines."
            )

        elif idx == 3:
            # Current-State Assumptions
            return (
                "### Inferred Operational Baseline\n\n"
                "1. Data is currently transferred manually between multiple incompatible tools or spreadsheets.\n"
                "2. Operational personnel spend significant weekly hours performing repetitive clerical reconciliation.\n"
                "3. Source systems operate on disparate authentication and schema conventions."
            )

        elif idx == 4:
            # Target-State Vision
            return (
                "### Target Operating Model\n\n"
                "Once deployed, the business processes will execute through an event-driven, observable "
                "pipeline:\n\n"
                "- Incoming records are captured automatically via webhooks or API adapters.\n"
                "- Validation logic guarantees ACID compliance before records enter the relational ledger.\n"
                "- Stakeholders receive automated notifications and real-time dashboard visibility."
            )

        elif idx == 5:
            # Recommended Technical Approach
            return (
                "### Systems Architecture: Python-First Modular Monolith\n\n"
                "- **Backend**: Python 3.12+ with FastAPI for high-performance asynchronous API endpoints.\n"
                "- **Persistence**: Microsoft SQL Server with SQLAlchemy 2.0 and Read Committed Snapshot Isolation (RCSI).\n"
                "- **Frontend**: Server-rendered HTML with Jinja2, HTMX for dynamic partial swaps, and Alpine.js for lightweight UI reactivity.\n"
                "- **Design Pattern**: Domain-driven modular monolith with strict encapsulation and zero circular dependencies."
            )

        elif idx == 6:
            # Core Functional Capabilities
            opp_list = "\n".join([f"- **{o.title}** ({o.category}): {o.description}" for o in opportunities]) or "- Centralized administrative operations console."
            return (
                f"### Key Functional Capabilities Matrix\n\n"
                f"The system provides the following core functional modules:\n\n"
                f"{opp_list}\n\n"
                f"- Role-based access control (Admin, Operator, Read-Only Auditor).\n"
                f"- Full audit log trail of all mutations."
            )

        elif idx == 7:
            # AI & Intelligence Components
            return (
                "### Cognitive Pipelines & Structured Extraction\n\n"
                "- **Zero-Retention API Integration**: All external model interactions utilize enterprise endpoints configured with zero training and zero data retention.\n"
                "- **Deterministic Pre-Transit Scrubbing**: PII regex sanitization strips sensitive identifiers before model transit.\n"
                "- **Strict Pydantic Validation**: All model outputs are strictly validated against typed schemas with deterministic fallback catalogs."
            )

        elif idx == 8:
            # Workflow Automations
            return (
                "### Event-Driven Workflows\n\n"
                "1. `Intake Event` -> Validates payload format -> Stages record in transactional queue.\n"
                "2. `Sync Event` -> Bridges staging record to downstream ERP/accounting ledger.\n"
                "3. `Notification Event` -> Dispatches status alerts to assigned operational staff."
            )

        elif idx == 9:
            # Third-Party API Integrations
            return (
                "### External System Interfaces\n\n"
                "- Authenticated REST/ODBC bridges to existing operational databases.\n"
                "- Webhook receivers with cryptographic signature verification.\n"
                "- Outbound email/notification dispatchers."
            )

        elif idx == 10:
            # Data Modeling & Storage Strategy
            return (
                "### Relational Schema Design\n\n"
                "- Master relational entities stored in Microsoft SQL Server (`dbo` schema).\n"
                "- Primary keys implemented as unique UUIDs (`UNIQUEIDENTIFIER`).\n"
                "- Timestamp tracking with UTC `DATETIME2` columns and foreign key cascade rules.\n"
                "- Append-only audit logs tracking all state mutations and actor identifiers."
            )

        elif idx == 11:
            # Security, Privacy & PII Guardrails
            return (
                "### Security & Data Protection Controls\n\n"
                "- **Session Security**: Cryptographically signed HMAC cookies (`SameSite=Lax`, `HttpOnly`).\n"
                "- **Database Protection**: Parameterized SQLAlchemy queries preventing SQL injection.\n"
                "- **PII Isolation**: Client-side and server-side redaction of credentials and personal identifiers.\n"
                "- **Input Validation**: Strict bounds and schema enforcement on all API routes."
            )

        elif idx == 12:
            # Deployment Topology & DevOps Strategy
            return (
                "### Deployment & Operations Baseline\n\n"
                "- **Development**: ₹0 local development environment on Windows 11 with SQL Server Express.\n"
                "- **Production**: Containerized deployment via Docker Compose behind an auto-TLS reverse proxy.\n"
                "- **Telemetry**: Health probes (`/health/live`, `/health/ready`) verifying process uptime and database ping."
            )

        elif idx == 13:
            # Project Delivery Milestones
            return (
                "### Structured 4-Milestone Delivery Schedule\n\n"
                "1. **Milestone 1: Foundation & Relational Schema** (2 Weeks) - Core database, migrations, and API scaffolding.\n"
                "2. **Milestone 2: Functional Engine & Integrations** (3-4 Weeks) - Core business logic, pipelines, and adapters.\n"
                "3. **Milestone 3: UI/UX & Staging Verification** (2 Weeks) - Frontend views, HTMX interactions, and UAT.\n"
                "4. **Milestone 4: Production Hardening & Hypercare** (1-2 Weeks) - Deployment, monitoring, and handover."
            )

        elif idx == 14:
            # Architectural Dependencies
            return (
                "### External Client Prerequisites\n\n"
                "- Access credentials and API documentation for existing operational systems.\n"
                "- Designated business domain expert for milestone acceptance reviews.\n"
                "- DNS and deployment target access for production deployment."
            )

        elif idx == 15:
            # Identified Technical & Business Risks
            return (
                "### Risk Register & Mitigations\n\n"
                "- **Risk**: Legacy API rate limits or lack of webhook triggers.\n"
                "  - *Mitigation*: Implement resilient polling workers with exponential backoff.\n"
                "- **Risk**: Inconsistent historical data formatting.\n"
                "  - *Mitigation*: Enforce automated data validation and cleaning rules at the staging gateway."
            )

        elif idx == 16:
            # Open Unknowns Requiring Discovery
            return (
                "### Key Scoping Unknowns\n\n"
                "- Exact schema formats of legacy exported files.\n"
                "- Peak concurrent operational user volume.\n"
                "- Specific compliance retention schedules required by client jurisdiction."
            )

        elif idx == 17:
            # Indicative Planning Parameters
            return (
                "### Indicative Investment & Timeline\n\n"
                "*(See Section 6 of Discovery Diagnostic for detailed indicative budget and timeline bands)*\n\n"
                "All planning ranges are algorithmic estimates and strictly subject to Principal Architect review."
            )

        elif idx == 18:
            # Human Review Gate & Commercial Next Step
            return (
                "### Commercial Next Steps\n\n"
                "To validate these architectural assumptions, schedule a formal scoping review with our "
                "senior engineering team. An architect will review your operational requirements and "
                "prepare a binding Statement of Work (SOW) within 24 business hours."
            )

        return f"### {sec_def.title}\n\n{sec_def.description}"
