"""initial_mvp_foundation

Revision ID: 4941998763bd
Revises: 
Create Date: 2026-09-07 17:03:55.580256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '4941998763bd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('session_id', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('ip_address_hash', sa.String(length=64), nullable=True),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('created_at', mssql.DATETIME2(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_table('leads',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('corporate_email', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=64), nullable=True),
    sa.Column('ip_country_code', sa.String(length=8), nullable=True),
    sa.Column('lead_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_corporate_email'), 'leads', ['corporate_email'], unique=False)
    op.create_table('discovery_sessions',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('session_token_hash', sa.String(length=64), nullable=False),
    sa.Column('current_stage', sa.String(length=32), nullable=False),
    sa.Column('is_unlocked', sa.Boolean(), nullable=False),
    sa.Column('lead_id', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), nullable=False),
    sa.Column('updated_at', mssql.DATETIME2(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discovery_sessions_session_token_hash'), 'discovery_sessions', ['session_token_hash'], unique=True)
    op.create_table('lead_consents',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('lead_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('consent_type', sa.String(length=64), nullable=False),
    sa.Column('consent_text', sa.Text(), nullable=False),
    sa.Column('granted_at', mssql.DATETIME2(), nullable=False),
    sa.Column('ip_address_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estimates',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('session_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('budget_min_inr', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('budget_max_inr', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('budget_min_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('budget_max_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('timeline_min_weeks', sa.Integer(), nullable=False),
    sa.Column('timeline_max_weeks', sa.Integer(), nullable=False),
    sa.Column('confidence_rating', sa.String(length=32), nullable=False),
    sa.Column('sizing_factors_json', sa.Text(), nullable=False),
    sa.Column('mandatory_disclaimer', sa.Text(), nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['discovery_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('opportunities',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('session_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('business_impact', sa.String(length=32), nullable=False),
    sa.Column('technical_complexity', sa.String(length=32), nullable=False),
    sa.Column('estimated_effort_weeks', sa.String(length=64), nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['discovery_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_session_id'), 'opportunities', ['session_id'], unique=False)
    op.create_table('problem_statements',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('session_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('sanitized_text', sa.Text(), nullable=False),
    sa.Column('character_count', sa.Integer(), nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), nullable=False),
    sa.CheckConstraint('character_count >= 20', name='chk_problem_character_count_min'),
    sa.ForeignKeyConstraint(['session_id'], ['discovery_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('review_requests',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('session_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('lead_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('request_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('assigned_architect', sa.String(length=128), nullable=True),
    sa.Column('created_at', mssql.DATETIME2(), nullable=False),
    sa.Column('triaged_at', mssql.DATETIME2(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['discovery_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solution_blueprints',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('session_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('blueprint_version', sa.Integer(), nullable=False),
    sa.Column('recommended_stack_category', sa.String(length=128), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_architect_endorsed', sa.Boolean(), nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), nullable=False),
    sa.Column('updated_at', mssql.DATETIME2(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['discovery_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('structured_contexts',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('session_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('clarification_answers', sa.Text(), nullable=False),
    sa.Column('core_challenge', sa.String(length=500), nullable=False),
    sa.Column('impacted_workflows', sa.Text(), nullable=False),
    sa.Column('flagged_unknowns', sa.Text(), nullable=False),
    sa.Column('complexity_tier', sa.String(length=32), nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['discovery_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('blueprint_sections',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('blueprint_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('section_index', sa.Integer(), nullable=False),
    sa.Column('section_key', sa.String(length=64), nullable=False),
    sa.Column('section_title', sa.String(length=255), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.Column('is_human_reviewed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['blueprint_id'], ['solution_blueprints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('IX_blueprint_sections_index', 'blueprint_sections', ['blueprint_id', 'section_index'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('IX_blueprint_sections_index', table_name='blueprint_sections')
    op.drop_table('blueprint_sections')
    op.drop_table('structured_contexts')
    op.drop_table('solution_blueprints')
    op.drop_table('review_requests')
    op.drop_table('problem_statements')
    op.drop_index(op.f('ix_opportunities_session_id'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_table('estimates')
    op.drop_table('lead_consents')
    op.drop_index(op.f('ix_discovery_sessions_session_token_hash'), table_name='discovery_sessions')
    op.drop_table('discovery_sessions')
    op.drop_index(op.f('ix_leads_corporate_email'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
